/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaOrgArticle: typeof import('@unhead/schema-org-vue')['SchemaOrgArticle']
    SchemaOrgBreadcrumb: typeof import('@unhead/schema-org-vue')['SchemaOrgBreadcrumb']
    SchemaOrgOrganization: typeof import('@unhead/schema-org-vue')['SchemaOrgOrganization']
    SchemaOrgWebPage: typeof import('@unhead/schema-org-vue')['SchemaOrgWebPage']
    SchemaOrgWebSite: typeof import('@unhead/schema-org-vue')['SchemaOrgWebSite']
  }
}
